version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  quarkus-app:
    image: my-quarkus-app:1.5
    container_name: quarkus-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      QUARKUS_LOG_CATEGORY__IO_AGROAL__LEVEL: DEBUG
    networks:
      - backend
  
  quarkus-native-app:
    image: bevilacqua96/my-quarkus-native-app:latest
    container_name: quarkus-native-app
    depends_on:
      - mysql
    environment:
      QUARKUS_MICROMETER_BINDER_SYSTEM: true
    ports:
      - "8082:8080"
    entrypoint: ["./application", "-Dquarkus.http.host=0.0.0.0", "-J-Xmx1g"]
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 1024M   # Hard limit (max memory usage)
  
  spring-native-app:
    image: bevilacqua96/my-spring-native-app:latest
    container_name: spring-native-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 50
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 5
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 1800000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 5000
    ports:
      - "8083:8081"
    entrypoint: ["./application", "-J-Xmx1g"]
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 1024M   # Hard limit (max memory usage)

  spring-app:
    image: my-spring-app:1.3
    container_name: spring-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8081:8081"
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - C:\Users\bruno\Desktop\Bruno\JUGSpringQuarkus\Infrastructure\prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  backend:
  monitoring:

volumes:
  mysql_data:
  prometheus_data:
