global:
  scrape_interval: 5s  # Coleta métricas a cada 5 segundos

scrape_configs:
  - job_name: "spring-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["spring-app:8081"]

  - job_name: "quarkus-app"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["quarkus-app:8080"]