name: Build Spring Boot Native Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-native:
    runs-on: ubuntu-latest  # Using Linux for GraalVM

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing variable paths
        run: |
            echo "GRAALVM_HOME: $GRAALVM_HOME"
            echo "JAVA_HOME: $JAVA_HOME"
            java --version
            native-image --version
    
      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x ./Spring-demo/demo/demo/mvnw

      - name: Build Native Image
        run: |
            cd Spring-demo/demo/demo
            ./mvnw clean package -Pnative -DskipTests

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: spring-native-binary
          path: Spring-demo/demo/demo/target/Spring-demo

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-native  # This ensures it waits for the first job to complete

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Native Binary from previous job
        uses: actions/download-artifact@v4
        with:
          name: spring-native-binary
          path: ./Spring-Demo
        

      - name: Build Docker Image using a better base image
        run: |
          # Build the Docker image using a more suitable base image (e.g., Alpine or distroless)
          cd Spring-demo/demo/demo/
          mkdir target
          cp -r ../../Spring-Demo ./target/
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-spring-native-app:latest -f Dockerfile.native .
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
  
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-spring-native-app:latest
