name: Build Quarkus Native Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-native:
    runs-on: ubuntu-latest  # Uses a Linux-based runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SDKMAN and GraalVM
        run: |
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install java 23.0.2-graalce  # Install latest GraalVM (update if needed)
            sdk use java 23.0.2-graalce
            $GRAALVM_HOME/bin/gu --version
            gu install native-image

      - name: Increase Swap Space for Memory (Optional)
        run: |
          sudo fallocate -l 6G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Set up Docker to Use More Memory
        run: |
          sudo sysctl -w vm.max_map_count=262144
          echo '{"builder": {"gc": {"enabled": true}}}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart

      - name: Install GraalVM Native Image
        run: gu install native-image

      - name: Build Quarkus Native Image
        run: |
          ./Quarkus-demo/demo/mvnw package -Pnative \
            -Dquarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21 \
            -Dquarkus.native.native-image-xmx=6G \
            -Dquarkus.native.native-image-options="--native-image-threads=2 --no-fallback"

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-native-binary
          path: Quarkus-demo/demo/target/*-runner

