name: Build Quarkus Native Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-native:
    runs-on: ubuntu-latest
    container: quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x ./Quarkus-demo/demo/mvnw
    
      - name: Debug Directory Structure
        run: ls -R

      - name: Build Quarkus Native Image
        run: |
          ./Quarkus-demo/demo/mvnw package -Pnative \
            -Dquarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21 \
            -Dquarkus.native.native-image-xmx=6G \
            -Dquarkus.native.native-image-options="--native-image-threads=2 --no-fallback"

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-native-binary
          path: Quarkus-demo/demo/target/*-runner

