name: Build Quarkus Native Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-native:
    runs-on: ubuntu-latest
    container: quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x ./Quarkus-demo/demo/mvnw

      - name: Build Quarkus Native Image
        run: |
            cd ./Quarkus-demo/demo/
            ./mvnw package -Pnative \
            -DskipTests

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-native-binary
          path: Quarkus-demo/demo/target/*-runner

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-native  # This ensures it waits for the first job to complete

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Native Binary from previous job
        uses: actions/download-artifact@v4
        with:
          name: quarkus-native-binary
          path: ./quarkus-binary-runner

      - name: Build Docker Image using a better base image
        run: |
          # Build the Docker image using a more suitable base image (e.g., Alpine or distroless)
          cd Quarkus-demo/demo/
          mkdir target
          cp -r ../../quarkus-binary-runner ./target/
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-quarkus-native-app:latest -f src/main/docker/Dockerfile.native .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-quarkus-native-app:latest

