name: Build Spring Boot Native Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-native:
    runs-on: ubuntu-latest  # Using Linux for GraalVM

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing variable paths
        run: |
            echo "GRAALVM_HOME: $GRAALVM_HOME"
            echo "JAVA_HOME: $JAVA_HOME"
            java --version
            native-image --version
    
      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x ./Spring-demo/demo/demo/mvnw

      - name: Build Native Image
        run: |
            cd Spring-demo/demo/demo
            ./mvnw -Pnative native:compile \
            -DskipTests

      - name: Build Docker Image
        run: |
            cd Spring-demo/demo/demo
            docker build -t my-spring-boot-native-app .
      
      - name: Push Docker Image
        if: success()
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-spring-boot-native-app my-docker-repo/my-spring-boot-native-app:latest
          docker push my-docker-repo/my-spring-boot-native-app:latest
