name: Build Quarkus Native Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-native:
    runs-on: ubuntu-latest
    container: quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x ./Quarkus-demo/demo/mvnw
    
      - name: Install Docker
        run: |
          yum install -y docker
          service docker start
          usermod -aG docker $USER

      - name: Build Quarkus Native Image
        run: |
            cd ./Quarkus-demo/demo/
            ./mvnw package -Pnative \
            -DskipTests

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-native-binary
          path: Quarkus-demo/demo/target/*-runner

      # Docker build and upload
      - name: Build Docker Image
        run: |
          cd ./Quarkus-demo/demo/
          docker build -t my-docker-repo/my-quarkus-native-app:latest -f src/main/docker/Dockerfile.native .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push my-docker-repo/my-quarkus-native-app:latest

